#ROS package you are documenting
package_name = "gps_waypoint_publisher"
repo = "https://youtu.be/oHg5SJYRHA0"

#You can have multiple nodes in one package
[[nodes]]
node_name = 'gps_waypoint_publisher'
#Relitive to this file
source_file = ['./gps_waypoint_publisher/gwp.py']
summary = '''
A node that converts a file of gps points into waypoints about map, then follows them using nav2.

This node requires the use of a magnometer and GPS.

In practice, this node will wait for an initalpoint to be published. When it is, it will then wait for a
new GPS and magnometer reading to be recived. While this is happening, the robot should not move. Once these
have been obtained, it will parse the gps points and convert them into local waypoints. Finally, it will begin 
to navigate through these points using nav2's waypoint_follower.
'''

[[nodes.subscribes]]
name = '/gps'
description = 'The source of gps data, used to find the gps point at the initalpose.'

[[nodes.subscribes]]
name = '/mag'
description = 'The source of magnometer data, used to find inital heading.'

[[nodes.subscribes]]
name = '/initalpose'
description = 'Standard initalpose. Assumed to be origin of map.'

[[nodes.params]]
name = 'filepath **(required)**'
description = 'Path to file of GPS points. This file should be `lat,long` pairs, seperated by newlines.'
