#ROS package you are documenting
package_name = "gps_waypoint_publisher"
repo = "https://youtu.be/oHg5SJYRHA0"

#You can have multiple nodes in one package
[[nodes]]
node_name = 'gps_waypoint_publisher'
#Relitive to this file
source_file = ['./gps_waypoint_publisher/gwp.py']
summary = '''
A node that converts a file of gps points into waypoints about map, then follows them using nav2.

This node requires the use of a magnometer and GPS.

In practice, this node will wait for an initalpoint to be published. When it is, it will wait for a pose message, where that pose
is ECEF coordinates, and its orientation is a rotation from north. This is designed to match the API of the Vectornav driver.
While this is happening, the robot should not move. Once these have been obtained, it will parse the gps points and convert them into local waypoints. Finally, it will
publish these poses for consumption by a node like waypoint_publisher.
'''

misc = 'To obtain non ROS dependancies, you must run pip install -r requirements.txt in this directory.'

[[nodes.subscribes]]
name = '/pose'
description = 'A pose containing the orientation relative to north, and x y z ECEF gps coordinates.'

[[nodes.subscribes]]
name = '/initalpose'
description = 'Standard initalpose. Assumed to be origin of map.'

[[nodes.publishes]]
name = '/gps/points'
description = 'The list of converted waypoints.'

[[nodes.params]]
name = 'filepath **(required)**'
description = 'Path to file of GPS points. This file should be `lat,long` pairs, seperated by newlines.'
